[package]
name = "zed_vue"
version = "0.1.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/vue.rs"
crate-type = ["cdylib"]

[dependencies]
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
zed_extension_api = "0.1.0"
